apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
  storageClassName: glusterfs-storage