name: Python Unit Testing

on: [push]

jobs:
  build:
    runs-on: python:3.8.6-slim-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Unit test
        run: |
          python -m unittest discover -s tests --pattern "*.py"